### ISSUE TITLE
Add console support for admin commands

### ISSUE THREAD

**Issue by Valtn** [DarkEyeDragon/RandomTeleport#251]
**Is your feature request related to a problem? Please describe.**
Unable to run admin commands through console.

```
[RandomTeleport] [ACF] java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.hasPermission(String)" because "this.player" is null
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//me.darkeyedragon.randomtp.world.PlayerSpigot.hasPermission(PlayerSpigot.java:85)
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//me.darkeyedragon.randomtp.common.command.RandomTeleportCommand.teleport(RandomTeleportCommand.java:177)
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//me.darkeyedragon.randomtp.common.command.RandomTeleportCommand.onTeleport(RandomTeleportCommand.java:155)
[RandomTeleport] [ACF]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[RandomTeleport] [ACF]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[RandomTeleport] [ACF]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[RandomTeleport] [ACF]        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//co.aikar.commands.BaseCommand.execute(BaseCommand.java:513)
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[RandomTeleport] [ACF]        at RandomTeleport-Spigot.jar//co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[RandomTeleport] [ACF]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[RandomTeleport] [ACF]        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[RandomTeleport] [ACF]        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:872)
[RandomTeleport] [ACF]        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:473)
[RandomTeleport] [ACF]        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[RandomTeleport] [ACF]        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
[RandomTeleport] [ACF]        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
[RandomTeleport] [ACF]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[RandomTeleport] [ACF]        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Describe the solution you'd like**
It would be great if you could allow admin commands (other than /rtp reload) to run from the console. I'm particularly interested in running /rtp resetcooldown from the console.

Also, the wiki has a typo in the reset cooldown command "/rtp resetcoodown".

**Comment by DarkEyeDragon** [comment]
Please use the template next time, its easier for me to figure out if you're on the last version or not.
You should be able to use console commands on the last versions.

Could you please create a new issue that follows the template?

**Comment by Valtn** [comment]
The **Feature request** template does not ask for a version.

---

**Describe the bug**
NullPointerException when running `/rtp resetcooldown` through the console at:

https://github.com/DarkEyeDragon/RandomTeleport/blob/134d79da0fe2aeb492d280b454779cb96885e176/Spigot/src/main/java/me/darkeyedragon/randomtp/world/PlayerSpigot.java#L85

**To Reproduce**
Steps to reproduce the behavior:
1. Type `/rtp resetcooldown <player>`

**Expected behavior**
Cooldown gets reset.

**Minecraft Version**
Paper version `git-Paper-58 (MC: 1.19)` (latest)

**Plugin version**
RandomTeleport-Spigot-3.0.0.179.jar

**Comment by DarkEyeDragon** [comment]
Yeah sorry i thought it did. My bad.

I'll look into fixing this. Thanks for reporting.
